id = "icons-modern-material"
name = "Icons modern material"
version = "1.0.2"
schema_version = 1
authors = ["JosMiguelMM <miguelmendezm0802@gmail.com>"]
description = "A collection of icons for Zed"
repository = "https://github.com/JosMiguelMM/icons-modern-material"
